#总体设置
site_name: Jack_Steve的个人网站
site_url: https://bilibilijacksteve.github.io/site/
site_author: Jack_Steve
site_description: my first site

plugins:
  - blog
  - tags

nav:
  - 笔记：
    - notes/考研知识.md
    - notes/danq.md
  - 测试：
    - notes/Untitled-1.md

theme:
  name: material

  palette:
    #toggle for light mode
    - scheme: default
      primary: grey
      accent: amber
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    #toggle for dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  
  language: zh

  copyright: Copyright &copy; 2025 - 2026 Jack_Steve